### ISSUE TITLE
Block scoped declarations not working on node v4

### ISSUE THREAD

**Issue by amoe** [doabit/vue-ssr-starter-kit#16]
I am trying to use the starter kit on node 4.3.1, but I get the following error.

    amoe@inktvis $ npm run dev
    > vue-ssr-starter-kit@0.0.0 dev /home/amoe/vcs/vue-ssr-starter-kit
    > node server

    /home/amoe/vcs/vue-ssr-starter-kit/server.js:11
    let renderer
    ^^^

    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Function.Module.runMain (module.js:441:10)
        at startup (node.js:134:18)
        at node.js:962:3

Putting in `"use strict";` to the files seems to fix it.  Would you consider adding this strict declaration, or documenting that the starter kit should only be used with a certain node version?

**Comment by doabit** [comment]
@amoe Sorry, i've updated README.

**Comment by amoe** [comment]
Thanks!
